package io.elegans.orac.entities

case class RecommendationHistory (
                                   id: Option[String], /** recommendation history id, it can be autogenerated */
                                   recommendation_id: String, /** recommendation id */
                                   access_user_id: Option[String], /** system user id who accessed to the recommendation */
                                   user_id: String, /** user id (from original recommendation) */
                                   item_id: String, /** item id (from original recommendation) */
                                   name: String, /** name (from original recommendation) */
                                   generation_batch: String, /** generation batch id */
                                   generation_timestamp: Long, /** generation timestamp (from original recommendation) */
                                   access_timestamp: Option[Long],  /** timestamp of recommendation access */
                                   score: Double /** recommendation score (from original recommendation) */
                                 )

case class RecommendationsHistory (
                             items: List[RecommendationHistory]
                           )